String n() throws Exception {
    return in.next();
}